# Travis CI

## Set language
language: ruby

## Use these Ruby versions
rvm:
- 2.2.0

# Test the gh-pages branch
branches:
  only:
  - gh-pages

## Run command
script: bundle exec jekyll build

## Speeds up installation of html-proofer
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

## Route your build to the container-based infrastructure for a faster build
sudo: false
