# Bunto / Jekyll settings

## Informations
title: Aahash de Ruffy
description: The official website of Aahash de Ruffy.
keywords: aahash, aahash de ruffy, github, acs, acp, isc host

url: "https://aahash.tk"
assets_url: "https://aahash.tk/assets"

email: aahashderuffy@users.noreply.github.com
github_username:  aahashderuffy

## Build settings
markdown: kramdown
theme: minima

## Included Gems / Plugins
gems:
  - jekyll-sitemap
